# --- Template Configuration ---
name: 'Create Issue'
description: 'Creates a Jira task and a branch corresponding to the Jira ticket number.'
title: '[issue] : {Issue Title}'

# --- Form Body ---
body:
  - type: dropdown
    id: type
    attributes:
      label: '🏷️ Issue Type (required)'
      description: 'Select the type of issue'
      options:
        - Bug
        - Feature
        - Task
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: '📝 Issue Description (required)'
      description: 'Describe the issue in detail'
      placeholder: |
        This template is linked with Jira to create a task and a branch corresponding to the Jira ticket number.
        Once the issue is created, check the comment for the generated branch name.
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '✅ Issue Checklist (optional)'
      description: 'List the tasks needed to resolve this issue'
      value: |
        - [ ] Task 1
        - [ ] Task 2

  - type: textarea
    id: reference
    attributes:
      label: '🔗 References (optional)'
      description: 'Add any links or images for reference.'
